spring:
  application:
    name: fxx_zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8090
zuul:
  routes:
    fxx_consumer:
      path: /fxxconsumer/**
      serviceId: fxx_consumer
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken

